/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as MakeRouteImport } from './routes/make'
import { Route as PlaceRouteImport } from './routes/place'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ProtectedFilesRouteImport } from './routes/_protected/files'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiUploadsIndexRouteImport } from './routes/api/uploads/index'
import { Route as ApiUploadsIdRouteImport } from './routes/api/uploads/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeRoute = MakeRouteImport.update({
  id: '/make',
  path: '/make',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceRoute = PlaceRouteImport.update({
  id: '/place',
  path: '/place',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedFilesRoute = ProtectedFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsIndexRoute = ApiUploadsIndexRouteImport.update({
  id: '/api/uploads/',
  path: '/api/uploads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsIdRoute = ApiUploadsIdRouteImport.update({
  id: '/api/uploads/$id',
  path: '/api/uploads/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/directory': typeof DirectoryRoute
  '/make': typeof MakeRoute
  '/place': typeof PlaceRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/files': typeof ProtectedFilesRoute
  '/product/$id': typeof ProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$id': typeof ApiUploadsIdRoute
  '/api/uploads/': typeof ApiUploadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/directory': typeof DirectoryRoute
  '/make': typeof MakeRoute
  '/place': typeof PlaceRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/files': typeof ProtectedFilesRoute
  '/product/$id': typeof ProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$id': typeof ApiUploadsIdRoute
  '/api/uploads': typeof ApiUploadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/directory': typeof DirectoryRoute
  '/make': typeof MakeRoute
  '/place': typeof PlaceRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_protected/files': typeof ProtectedFilesRoute
  '/product/$id': typeof ProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$id': typeof ApiUploadsIdRoute
  '/api/uploads/': typeof ApiUploadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/directory'
    | '/make'
    | '/place'
    | '/sign-in'
    | '/sign-up'
    | '/files'
    | '/product/$id'
    | '/api/auth/$'
    | '/api/uploads/$id'
    | '/api/uploads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/directory'
    | '/make'
    | '/place'
    | '/sign-in'
    | '/sign-up'
    | '/files'
    | '/product/$id'
    | '/api/auth/$'
    | '/api/uploads/$id'
    | '/api/uploads'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/directory'
    | '/make'
    | '/place'
    | '/sign-in'
    | '/sign-up'
    | '/_protected/files'
    | '/product/$id'
    | '/api/auth/$'
    | '/api/uploads/$id'
    | '/api/uploads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  DirectoryRoute: typeof DirectoryRoute
  MakeRoute: typeof MakeRoute
  PlaceRoute: typeof PlaceRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUploadsIdRoute: typeof ApiUploadsIdRoute
  ApiUploadsIndexRoute: typeof ApiUploadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make': {
      id: '/make'
      path: '/make'
      fullPath: '/make'
      preLoaderRoute: typeof MakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place': {
      id: '/place'
      path: '/place'
      fullPath: '/place'
      preLoaderRoute: typeof PlaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/files': {
      id: '/_protected/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof ProtectedFilesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/': {
      id: '/api/uploads/'
      path: '/api/uploads'
      fullPath: '/api/uploads/'
      preLoaderRoute: typeof ApiUploadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$id': {
      id: '/api/uploads/$id'
      path: '/api/uploads/$id'
      fullPath: '/api/uploads/$id'
      preLoaderRoute: typeof ApiUploadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedFilesRoute: typeof ProtectedFilesRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedFilesRoute: ProtectedFilesRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  DirectoryRoute: DirectoryRoute,
  MakeRoute: MakeRoute,
  PlaceRoute: PlaceRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ProductIdRoute: ProductIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUploadsIdRoute: ApiUploadsIdRoute,
  ApiUploadsIndexRoute: ApiUploadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
