/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as MakeRouteImport } from './routes/make'
import { Route as PlaceRouteImport } from './routes/place'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeRoute = MakeRouteImport.update({
  id: '/make',
  path: '/make',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceRoute = PlaceRouteImport.update({
  id: '/place',
  path: '/place',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/directory': typeof DirectoryRoute
  '/make': typeof MakeRoute
  '/place': typeof PlaceRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/directory': typeof DirectoryRoute
  '/make': typeof MakeRoute
  '/place': typeof PlaceRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/directory': typeof DirectoryRoute
  '/make': typeof MakeRoute
  '/place': typeof PlaceRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/directory' | '/make' | '/place' | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/directory' | '/make' | '/place' | '/product/$id'
  id: '__root__' | '/' | '/directory' | '/make' | '/place' | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectoryRoute: typeof DirectoryRoute
  MakeRoute: typeof MakeRoute
  PlaceRoute: typeof PlaceRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make': {
      id: '/make'
      path: '/make'
      fullPath: '/make'
      preLoaderRoute: typeof MakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place': {
      id: '/place'
      path: '/place'
      fullPath: '/place'
      preLoaderRoute: typeof PlaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectoryRoute: DirectoryRoute,
  MakeRoute: MakeRoute,
  PlaceRoute: PlaceRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
