/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as MakeRouteImport } from './routes/make'
import { Route as PlaceRouteImport } from './routes/place'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedFilesRouteImport } from './routes/_protected/files'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as StickerIdRouteImport } from './routes/sticker.$id'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStickersIndexRouteImport } from './routes/api/stickers/index'
import { Route as ApiStickersIdRouteImport } from './routes/api/stickers/$id'
import { Route as ApiUploadsIndexRouteImport } from './routes/api/uploads/index'
import { Route as ApiUploadsIdRouteImport } from './routes/api/uploads/$id'
import { Route as ProtectedDashboardProductsIdRouteImport } from './routes/_protected/dashboard/products.$id'
import { Route as ProtectedDashboardStickersIdRouteImport } from './routes/_protected/dashboard/stickers.$id'
import { Route as ApiStickersIdImageRouteImport } from './routes/api/stickers/$id.image'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeRoute = MakeRouteImport.update({
  id: '/make',
  path: '/make',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceRoute = PlaceRouteImport.update({
  id: '/place',
  path: '/place',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFilesRoute = ProtectedFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StickerIdRoute = StickerIdRouteImport.update({
  id: '/sticker/$id',
  path: '/sticker/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStickersIndexRoute = ApiStickersIndexRouteImport.update({
  id: '/api/stickers/',
  path: '/api/stickers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStickersIdRoute = ApiStickersIdRouteImport.update({
  id: '/api/stickers/$id',
  path: '/api/stickers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsIndexRoute = ApiUploadsIndexRouteImport.update({
  id: '/api/uploads/',
  path: '/api/uploads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsIdRoute = ApiUploadsIdRouteImport.update({
  id: '/api/uploads/$id',
  path: '/api/uploads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardProductsIdRoute =
  ProtectedDashboardProductsIdRouteImport.update({
    id: '/products/$id',
    path: '/products/$id',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardStickersIdRoute =
  ProtectedDashboardStickersIdRouteImport.update({
    id: '/stickers/$id',
    path: '/stickers/$id',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ApiStickersIdImageRoute = ApiStickersIdImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => ApiStickersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/directory': typeof DirectoryRoute
  '/make': typeof MakeRoute
  '/place': typeof PlaceRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/files': typeof ProtectedFilesRoute
  '/product/$id': typeof ProductIdRoute
  '/sticker/$id': typeof StickerIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stickers/$id': typeof ApiStickersIdRouteWithChildren
  '/api/uploads/$id': typeof ApiUploadsIdRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/api/stickers/': typeof ApiStickersIndexRoute
  '/api/uploads/': typeof ApiUploadsIndexRoute
  '/dashboard/products/$id': typeof ProtectedDashboardProductsIdRoute
  '/dashboard/stickers/$id': typeof ProtectedDashboardStickersIdRoute
  '/api/stickers/$id/image': typeof ApiStickersIdImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/directory': typeof DirectoryRoute
  '/make': typeof MakeRoute
  '/place': typeof PlaceRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/files': typeof ProtectedFilesRoute
  '/product/$id': typeof ProductIdRoute
  '/sticker/$id': typeof StickerIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stickers/$id': typeof ApiStickersIdRouteWithChildren
  '/api/uploads/$id': typeof ApiUploadsIdRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/api/stickers': typeof ApiStickersIndexRoute
  '/api/uploads': typeof ApiUploadsIndexRoute
  '/dashboard/products/$id': typeof ProtectedDashboardProductsIdRoute
  '/dashboard/stickers/$id': typeof ProtectedDashboardStickersIdRoute
  '/api/stickers/$id/image': typeof ApiStickersIdImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/directory': typeof DirectoryRoute
  '/make': typeof MakeRoute
  '/place': typeof PlaceRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_protected/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/_protected/files': typeof ProtectedFilesRoute
  '/product/$id': typeof ProductIdRoute
  '/sticker/$id': typeof StickerIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stickers/$id': typeof ApiStickersIdRouteWithChildren
  '/api/uploads/$id': typeof ApiUploadsIdRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/api/stickers/': typeof ApiStickersIndexRoute
  '/api/uploads/': typeof ApiUploadsIndexRoute
  '/_protected/dashboard/products/$id': typeof ProtectedDashboardProductsIdRoute
  '/_protected/dashboard/stickers/$id': typeof ProtectedDashboardStickersIdRoute
  '/api/stickers/$id/image': typeof ApiStickersIdImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/directory'
    | '/make'
    | '/place'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/files'
    | '/product/$id'
    | '/sticker/$id'
    | '/api/auth/$'
    | '/api/stickers/$id'
    | '/api/uploads/$id'
    | '/dashboard/'
    | '/api/stickers/'
    | '/api/uploads/'
    | '/dashboard/products/$id'
    | '/dashboard/stickers/$id'
    | '/api/stickers/$id/image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/directory'
    | '/make'
    | '/place'
    | '/sign-in'
    | '/sign-up'
    | '/files'
    | '/product/$id'
    | '/sticker/$id'
    | '/api/auth/$'
    | '/api/stickers/$id'
    | '/api/uploads/$id'
    | '/dashboard'
    | '/api/stickers'
    | '/api/uploads'
    | '/dashboard/products/$id'
    | '/dashboard/stickers/$id'
    | '/api/stickers/$id/image'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/directory'
    | '/make'
    | '/place'
    | '/sign-in'
    | '/sign-up'
    | '/_protected/dashboard'
    | '/_protected/files'
    | '/product/$id'
    | '/sticker/$id'
    | '/api/auth/$'
    | '/api/stickers/$id'
    | '/api/uploads/$id'
    | '/_protected/dashboard/'
    | '/api/stickers/'
    | '/api/uploads/'
    | '/_protected/dashboard/products/$id'
    | '/_protected/dashboard/stickers/$id'
    | '/api/stickers/$id/image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  DirectoryRoute: typeof DirectoryRoute
  MakeRoute: typeof MakeRoute
  PlaceRoute: typeof PlaceRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ProductIdRoute: typeof ProductIdRoute
  StickerIdRoute: typeof StickerIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStickersIdRoute: typeof ApiStickersIdRouteWithChildren
  ApiUploadsIdRoute: typeof ApiUploadsIdRoute
  ApiStickersIndexRoute: typeof ApiStickersIndexRoute
  ApiUploadsIndexRoute: typeof ApiUploadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make': {
      id: '/make'
      path: '/make'
      fullPath: '/make'
      preLoaderRoute: typeof MakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place': {
      id: '/place'
      path: '/place'
      fullPath: '/place'
      preLoaderRoute: typeof PlaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/files': {
      id: '/_protected/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof ProtectedFilesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sticker/$id': {
      id: '/sticker/$id'
      path: '/sticker/$id'
      fullPath: '/sticker/$id'
      preLoaderRoute: typeof StickerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stickers/': {
      id: '/api/stickers/'
      path: '/api/stickers'
      fullPath: '/api/stickers/'
      preLoaderRoute: typeof ApiStickersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stickers/$id': {
      id: '/api/stickers/$id'
      path: '/api/stickers/$id'
      fullPath: '/api/stickers/$id'
      preLoaderRoute: typeof ApiStickersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/': {
      id: '/api/uploads/'
      path: '/api/uploads'
      fullPath: '/api/uploads/'
      preLoaderRoute: typeof ApiUploadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$id': {
      id: '/api/uploads/$id'
      path: '/api/uploads/$id'
      fullPath: '/api/uploads/$id'
      preLoaderRoute: typeof ApiUploadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/products/$id': {
      id: '/_protected/dashboard/products/$id'
      path: '/products/$id'
      fullPath: '/dashboard/products/$id'
      preLoaderRoute: typeof ProtectedDashboardProductsIdRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/stickers/$id': {
      id: '/_protected/dashboard/stickers/$id'
      path: '/stickers/$id'
      fullPath: '/dashboard/stickers/$id'
      preLoaderRoute: typeof ProtectedDashboardStickersIdRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/api/stickers/$id/image': {
      id: '/api/stickers/$id/image'
      path: '/image'
      fullPath: '/api/stickers/$id/image'
      preLoaderRoute: typeof ApiStickersIdImageRouteImport
      parentRoute: typeof ApiStickersIdRoute
    }
  }
}

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedDashboardProductsIdRoute: typeof ProtectedDashboardProductsIdRoute
  ProtectedDashboardStickersIdRoute: typeof ProtectedDashboardStickersIdRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedDashboardProductsIdRoute: ProtectedDashboardProductsIdRoute,
  ProtectedDashboardStickersIdRoute: ProtectedDashboardStickersIdRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
  ProtectedFilesRoute: typeof ProtectedFilesRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
  ProtectedFilesRoute: ProtectedFilesRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface ApiStickersIdRouteChildren {
  ApiStickersIdImageRoute: typeof ApiStickersIdImageRoute
}

const ApiStickersIdRouteChildren: ApiStickersIdRouteChildren = {
  ApiStickersIdImageRoute: ApiStickersIdImageRoute,
}

const ApiStickersIdRouteWithChildren = ApiStickersIdRoute._addFileChildren(
  ApiStickersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  DirectoryRoute: DirectoryRoute,
  MakeRoute: MakeRoute,
  PlaceRoute: PlaceRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ProductIdRoute: ProductIdRoute,
  StickerIdRoute: StickerIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStickersIdRoute: ApiStickersIdRouteWithChildren,
  ApiUploadsIdRoute: ApiUploadsIdRoute,
  ApiStickersIndexRoute: ApiStickersIndexRoute,
  ApiUploadsIndexRoute: ApiUploadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
